[[redirects]]
  from = "https://todo.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/todo/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "https://sortinghat.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/sortinghat/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"