[build]
functions = "./functions"

[[redirects]]
  from = "https://todo.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/todo/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "https://sortinghat.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/sortinghat/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "https://faces.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/faces/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "https://mariachi.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/mariachi/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "https://walk.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/walk/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"
[[redirects]]
  from = "https://regex-mistery.cgreinhold.dev/"
  to = "https://happy-swanson-106098.netlify.app/regex-mistery/"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"