##############################################################################
# Content
##############################################################################

# Set the page direction to RTL or LTR. default is LTR. (if you set it 'rtl', the 'vazir' font will be loaded.)
direction: ltr
# Configure the navigation menu.
# A pair 'Key: url' will result in a link to 'url' with the name 'Key' in the
# navigation menu. Optionally, you can add translations for the 'Key' in
# languages/*.yml
language: pt

nav:
  home: /
  about: /about/
  articles: /archives/
  projects: /projects/
  reading: /reading/

projects:
  - ideas:
    name: '101 Coisas'
    description: '101 coisas não convencionais para fazer esse ano'
    image: /images/seletor/seletor.png
    url: https://todo.cgreinhold.dev/
  - sortinghat:
    name: 'Chapéu Seletor'
    description: 'O Chapéu Seletor irá indicar qual seu caminho na programação'
    image: /images/seletor/seletor.png
    url: https://sortinghat.cgreinhold.dev/
  - cgrcode:
    name: CGRCode
    description: Uma alternativa ao famoso QRCode
    image: /images/cgrcode/cgrcode.gif
    url: https://cgreinhold.dev/2020/05/07/cgrcode/
  - palavras:
    name: Palavras
    description: Faça pontos encontrando palavras nesse pequeno jogo
    image: /images/palavras.PNG
    url: https://cgreinhold.dev/2020/05/25/word-games/
  - bolao:
    name: Bolão da copa
    description: Aplicativo de apostas da Copa do Mundo 2018
    image: /images/bolaoDaCopa.PNG
    url: https://github.com/CGReinhold/BolaoDaCopa/
  - bolao:
    name: Freecell
    description: Freecell para CLI construído com React
    image: /images/cards/freecell.gif
    url: https://cgreinhold.dev/2020/10/12/freecell/
  - brick:
    name: Brick game
    description: Relembre o antigo brick game em sua versão web
    image: /images/brick/brickgame2.png
    url: https://cgreinhold.dev/2020/07/28/brick/
  - superoctagon:
    name: Super Octagon
    description: Clone fajuto do jogo Super Hexagon
    image: /images/octagon.png
    url: https://cgreinhold.dev/2020/09/29/super-octagon/
  - clippy:
    name: Clippy
    description: Reviva a assistente clippy em seu computador
    image: /images/clippy.gif
    url: https://cgreinhold.dev/2019/08/25/clippy-revival/

# Links to your social media accounts.
# The keys should correspond to Fontawesome icon names
# (see https://fontawesome.com/icons?d=gallery&s=brands);
# only 'mail' is an exception.
social_links:
  github: https://github.com/cgreinhold
  linkedin: https://www.linkedin.com/in/cleyson-reinhold/
  mail: mailto:cleyson.reinhold@gmail.com
  rss: /feed.xml

# Customize the overview with displaying a tagcloud on the index page.
# Options: https://hexo.io/docs/helpers.html#tagcloud
tags_overview: false

# Customize the overview with the most recent blog posts on the index page.
# Options:
#   - show_all_posts: whether to show all available posts.
#   - post_count: whether to show only the x most recent posts.
#   - sort_updated: sort posts by last modification date instead of creation date.
posts_overview:
  show_all_posts: true
  # post_count: 200
  sort_updated: false

# Customize the archive view.
# Options:
#   - sort_updated: sort posts by last modification date instead of creation date.
# Note: this does not work together with pagination, since the pagination
# plugin will sort pages by date of creation.
archive:
  sort_updated: false

# Customize the article view.
# Options:
#   - show_updated: show the last modification date.
post:
  show_updated: false

##############################################################################
# Look and Feel
##############################################################################

# Customize the logo (i.e., the cactus) in the header.
# Options:
#   - enabled: whether to show (true) or hide (false) the logo.
#   - width: width of the logo in pixel units
#   - height: height of the logo in pixel units
#   - url: where the logo can be found
#   - gravatar: whether to use your Gravatar as the logo
logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false

# Customize the favicons.
# Cactus supports a limited set of the three most important icons:
#   - desktop: The classic favion.ico file.
#   - android: A 192x192 PNG file.
#   - apple:  A 180x180 PNG file.
# These can be generated with https://realfavicongenerator.net/
# Options:
#   - url: where the icon can be found
#   - gravatar: whether to create a favicon from your Gravatar
favicon:
  desktop:
    url: /images/favicon.ico
    gravatar: false
  android:
    url: /images/favicon-192x192.png
    gravatar: false
  apple:
    url: /images/apple-touch-icon.png
    gravatar: false

# The color scheme that should be used to highlight codeblocks.
# See source/css/_highlight for a list of all available color schemes.
# highlight: rainbow

# Set the color scheme.
# Available color schemes are 'dark', 'light', 'classic' and 'white'.
# Alternatively, add your own custom color scheme to source/css/_colors.
colorscheme: white

# Maximal width of the page in rem units.
page_width: 48


##############################################################################
# Miscellaneous
##############################################################################

# Enable or disable the RSS feed.
rss: false
